services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"  # Required for certbot HTTP challenge
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot  # Certbot challenges directory
      - ./certbot/conf:/etc/letsencrypt  # SSL certs storage
      - ./index.html:/var/www/html/index.html
    networks:
      lab-webproxy:
        ipv4_address: 10.11.0.6
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      lab-webproxy:
        ipv4_address: 10.11.0.7

networks:
  lab-webproxy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/16
          gateway: 10.11.0.1