name: Test NGINX Reverse Proxy with Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose jq

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: List running containers
        run: docker ps -a

      - name: Show docker-compose services status
        run: docker-compose ps

      - name: Show backend container logs
        run: docker logs app || echo "No logs for backend"

      - name: Show nginx container logs
        run: docker logs nginxwebsvr || echo "No logs for nginx"

      - name: Show backend container IP and test direct access
        run: |
          IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ssd-prac-reference-app)
          echo "Backend IP: $IP"
          curl -v http://$IP/api/hello || echo "Failed to curl backend IP"

      - name: Wait for backend readiness
        run: |
          for i in {1..10}; do
            if curl -s http://localhost/api/hello | jq -e '.message == "Hello from backend!"' > /dev/null; then
              echo "Backend is ready!"
              exit 0
            else
              echo "Waiting for backend..."
              sleep 3
            fi
          done
          echo "Backend did not become ready in time"
          exit 1

      - name: Tear down containers
        run: docker-compose down
