name: Test NGINX Reverse Proxy with Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose jq

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for services to start
        run: sleep 15  # Adjust this if your backend takes longer to start

      - name: Validate JSON response from /api/hello
        run: |
          response=$(curl -s http://localhost/api/hello)
          echo "$response"
          echo "$response" | jq -e '.message == "Hello from backend!"'

      - name: Tear down containers
        run: docker-compose down
