name: Test NGINX Reverse Proxy with Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for backend to start
        run: sleep 10

      - name: Test reverse proxy /api/hello endpoint
        run: curl -s http://localhost/api/hello | grep '{\"message\":\"Hello from backend!\"}'

      - name: Tear down containers
        run: docker-compose down
