name: Test NGINX Reverse Proxy with Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-docker-compose@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for backend readiness
        run: |
          for i in {1..10}; do
            if curl -s http://localhost/api/hello | jq -e '.message == "Hello from backend!"' > /dev/null; then
              echo "Backend is ready!"
              exit 0
            else
              echo "Waiting for backend..."
              sleep 3
            fi
          done
          echo "Backend did not become ready in time"
          exit 1

      - name: Tear down containers
        run: docker-compose down
